/*
 *  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 *  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE. IT CAN BE DISTRIBUTED FREE OF CHARGE AS LONG AS THIS HEADER 
 *  REMAINS UNCHANGED.
 *
 *  REPO: http://www.github.com/tomwilsoncoder/RTS
*/
using System;

[Flags]
public enum HotloaderValueType { 
    
    NONE =          0x00,


    NUMERICAL =     0x01,
    
    BOOLEAN =       0x02,

    DECIMAL =       0x04 | NUMERICAL,

    STRING =        0x08,

    VARIABLE =      0x1000, 
    EVALUATION =    0x2000, /*sub-evaluation e.g 1*(3*5)*/
}