/*
 *  THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 *  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 *  PURPOSE. IT CAN BE DISTRIBUTED FREE OF CHARGE AS LONG AS THIS HEADER 
 *  REMAINS UNCHANGED.
 *
 *  REPO: http://www.github.com/tomwilsoncoder/RTS
*/
using System;


[Flags]
public enum Direction : byte {
    NONE = 0,

    NORTH = 0x01,
    SOUTH = 0x02,

    WEST = 0x04,
    EAST = 0X08,

    NORTH_WEST = NORTH | WEST,
    NORTH_EAST = NORTH | EAST,

    SOUTH_WEST = SOUTH | WEST,
    SOUTH_EAST = SOUTH | EAST
}